global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-1'
    static_configs:
      - targets: ['node-1:8080']

  - job_name: 'node-2'
    static_configs:
      - targets: ['node-2:8080']

  - job_name: 'node-3'
    static_configs:
      - targets: ['node-3:8080']

  - job_name: 'node-4'
    static_configs:
      - targets: ['node-4:8080']